tickets/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
#from .views import (
    #TicketCreateAPIView,
    #TicketDeleteAPIView,
    #TicketDetailAPIView,
    #TicketListAPIView,
    #TicketUpdateAPIView,
#    )
#from rest_framework import routers

"""
router = routers.DefaultRouter()
router.register('tickets', views.TicketViewSet, basename='tickets-list')
#router.register(r'my-model/', MyModelView, basename='MyModel')

urlpatterns = [
    path('', include(router.urls)),

    #path('tickets/list/', TicketListAPIView, name='List'),
    #path('tickets/<int:id>/', TicketDetailAPIView, name='Detail'),
    #path('tickets/update/<int:id>/', TicketUpdateAPIView, name='Update'),
    #path('tickets/delete/<int:id>/', TicketDeleteAPIView, name='Delete'),
]
"""

app_name = 'tickets'

urlpatterns = [
    #path('', views.TicketListView.as_view(), name="list"),
    #path('<int:id>/', views.TicketDetailView.as_view(), name="detail"),
    #path('<int:id>/update/', views.TicketUpdateView.as_view(), name="update"),
    #path('<int:id>/delete/', views.TicketDeleteView.as_view(), name="delete"),

    #url(r'^$', views.list_tickets, name="listsss"),
    #url(r'^listss/$|^$', views.TicketList.as_view()),
    url(r'^list/$|^$', views.list_tickets, name="listss"),
    url(r'^tickets/api/list/$|^tickets/api/$', views.list_tickets, name="listsss"),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.ticket_detail, name="detailss"),
    url(r'^tickets/api/detail/(?P<pk>[0-9]+)/$', views.ticket_detail, name="detailsss"),
    #url(r'^details/(?P<pk>[0-9]+)/$', views.TicketList.as_view(), name="detailsss"),
    url(r'^tickets/api/detail/(?P<pk>[0-9]+)/update/$', views.ticket_detail, name="updatess"),
    url(r'^tickets/api/detail/(?P<pk>[0-9]+)/update/$', views.ticket_detail, name="updatesss"),
    #url(r'^tickets/api/detail/(?P<pk>[0-9]+)/delete/$', views.ticket_detail, name="deletess"),
    url(r'^action/newticket/$', views.new_ticket, name="newss"),
    url(r'^tickets/api/action/newticket/$', views.new_ticket, name="newsss"),
	url(r'^tickets/api/action/(?P<pk>[0-9]+)/delete/$', views.delete_ticket, name="deletesss"),
	#url(r'^action/deleteticket/$', views.delete_ticket, name="deletesss"),
    url(r'^action/login/$', views.account_login, name="loginss"),
    url(r'^action/logout/$', views.account_logout, name="logoutss"),
    url(r'^tickets/api/action/login/$', views.account_login, name="loginsss"),
    url(r'^tickets/api/action/logout/$', views.account_logout, name="logoutsss"),
    #path('action/<int:id>/updatess/', views.update_ticket, name="updatess"),
    #path('action/<int:id>/deletess/', views.delete_ticket, name="deletess"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

tickets/forms.py
from django import forms
from django.forms import ModelForm
from .models import Ticket
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

class TextareaWidget(forms.Textarea):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('attrs', {}).update({'rows': 20, 'cols': 100})
        super(TextareaWidget, self).__init__(*args, **kwargs)

class Textarea(forms.Field):
    widget = TextareaWidget()

"""
class TicketForm(forms.Form):
    class Meta:
        model = Ticket
        fields = '__all__'
        #fields = ['id', 'subject', 'message', 'ticket_type', 'ticket_status', 'updated']

    def save(requestobj, self):
        # By James Chen
        # Extend form class to have the save attribute
        # check paramters
        #data = self.cleaned_data
        #scope

        #if user.is_authenticated:

        data = request.POST
        id = data['id']
        subject = data['subject']
        message = data['message']
        type = data['ticket_type']
        status = data['ticket_status']
        update = data['updated']

        #name_map = {"id": request.POST['id'],"subject": request.POST['subject'],"message": request.POST['message'],"ticket_status": request.POST['ticket_status'],"ticket_type": request.POST['ticket_type'],"updated": request.POST['updated']}
        name_map = {"id": requestobj['id'],"subject": requestobj['subject'],"message": requestobj['message'],"ticket_status": requestobj['ticket_status'],"ticket_type": requestobj['ticket_type'],"updated": requestobj['updated']}
        Ticket.objects.raw("insert into tickets_ticket ('id', 'subject', 'message', 'ticket_status', 'ticket_type', 'updated') values (requestobj['id'], requestobj['subject'], requestobj['message'], requestobj['ticket_status'], requestobj['ticket_type'], requestobj['updated'])", translations=name_map)
        #ticket = Ticket({'id':requestobj['id'], 'subject':requestobj['subject'],'message':requestobj['message'],'ticket_type':requestobj['ticket_type'],'ticket_status':requestobj['ticket_status'],'updated':requestobj['updated']})



        #return redirect("tickets:listsss")
        # open connection
        # execute


"""

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = '__all__'
        #fields = ['id', 'subject', 'message', 'ticket_type', 'ticket_status', 'updated']

    id = forms.IntegerField(label="Bug id")
	
    subject = forms.CharField(label="Subject")
    #message = forms.CharField(label="Message", widget=forms.Textarea)
    message = Textarea()

    DEFECT = 'D'
    FEATURE = 'F'
    PATCH = 'P'

    #TICKET_TYPE = (
    #    (DEFECT, 'Defect'),
    #    (FEATURE, 'Feature'),
    #    (PATCH, 'Patch'),
    #)

    ticket_type = forms.ChoiceField(choices=[(DEFECT, 'Defect'), (FEATURE, 'Feature'), (PATCH, 'Patch'),])

    NEW = 'N'
    READ = 'RD'
    WAITING = 'W'
    REOPENED = 'RO'
    RESOLVED = 'R'


    #TICKET_STATUS = (
    #    (NEW, 'New'),
    #    (READ, 'Read'),
    #    (WAITING, 'Waiting'),
    #    (REOPENED, 'Reopened'),
    #    (RESOLVED, 'Resolved'),
    #)

    #ticket_type = forms.ModelChoiceField(queryset=TICKET_TYPE, empty_label="Select Ticket Type")
    ticket_status = forms.ChoiceField(choices=[(NEW, 'New'),(READ, 'Read'),(WAITING, 'Waiting'),(REOPENED, 'Reopened'),(RESOLVED, 'Resolved')])
    #updated = forms.DateField(input_formats=['%Y-%m-%d %H:%M:%S'])
    #updated = forms.DateField(input_formats=['%Y-%m-%d %H:%M:%S'])
    updated = forms.DateField(input_formats=['%Y-%m-%d'])
    owner = forms.CharField(label='Owner', max_length=18)
    # attachment = forms.ImageField()
	
class UserForm(forms.Form):
    class Meta:
        model = User
        fields = '__all__'

tickets/templates/tickets/delete_ticket.html
{% extends "base.html" %}
{% load rest_framework %}
{% block title %}
Pybugs - Delete Bugs
{% endblock title %}

{% block content %}
  <style type="text/css">
    .list-tickets-width { width: 750px; }
  </style>
  {% if user.is_authenticated %}
  <h1>add bugs {{ user }}</h1>
  <a href="{% url "tickets:loginsss" %}">Log In</a>
  <a href="{% url "tickets:logoutsss" %}" %}">Logout</a>
  <a href="{% url "tickets:newsss" %}">New Ticket</a>
  <a href="{% url "tickets:listsss" %}">List Ticket</a>
  {% else %}
  <h1>add bugs</h1>
  {% endif %}
  <div class="jcyc asnyc-data"></div>
  {% if request.user.is_authenticated %}
  <section class="jcyc ticket-form">
    <form method="POST"> 
        <!-- Security token by Django -->
        {% csrf_token %} 
        Are you want to delete this item ? 
        <input type="submit" value="Yes" /> 
        <a href="/tickets/api/list/">Cancel </a> 
    </form> 
  </section>
  {% endif %}
{% endblock content %}

{% block footer %}
<script type="text/javascript">

</script>
{% endblock %}

tickets/templates/tickets/list_tickets.html
{% extends "base.html" %}
{% load rest_framework %}

{% block title %}
Pybugs - List Bugs
{% endblock title %}

{% block content %}
  <!--<h1>{{ user.username }}</h1>-->
  <style type="">
    .txt-align-left { text-align: left; }
    .list-tickets-width { width: 750px; }
    .top-menu { margin: 0 auto 50px; }
    .top-menu a, .top-menu a:active, .top-menu a:hover { color: #FFFFFF; background-color: #000000 }
    .username { color: #FFFFFF; }
    .ticket-form { margin-top: 50px; text-align: left; }
    .list-new-tickets-p {margin: 15px 0; }
    .forms-panel { margin:0 auto; }
    .list-tickets-table { margin: 0 auto; }
    .forms-panel-table { margin: 0 auto; width:500px; height:400px; }
    #id_ticket_type { width: 165px; } 
    #id_ticket_status { width: 165px; }
  </style>
  <p class="jcyc top-menu" style="text-align:right;">
    <span class="jcyc username">{{ user.username }}</span>
    <a href="{% url 'tickets:loginsss' %}">Log In</a>
    <a href="{% url 'tickets:logoutsss' %}">Logout</a>
    <a href="{% url 'tickets:newsss' %}">New Ticket</a>
    <a href="{% url 'tickets:listsss' %}">List Tickets</a>
  </p>
  
<div class="jcyc list-tickets-table">
  <table class="jcyc list-tickets-table" style="text-align:center; border:1px solid #000000;">
    <thead>
        <tr style="background-color: #c1c1c1;">
          <td>Bug #</td>
          <td>Subject</td>
          <!--<td>Message</td>-->
          <td>Last Updated</td>
          <td>Owner</td>
          <td>Bug Processor</td>
		  <!--<td>Action</td>-->
        </tr>
    </thead>

    {% for ticket in tickets %}
      <tr class="ticket">
        <td><a href="{% url "tickets:updatesss" ticket.id %}">{{ ticket.id }}</a></td>
        <td style="text-align:left;"><a href="{% url "tickets:updatesss" ticket.id %}">{{ ticket.subject }}</a></td>
        <!--<td style="text-align:left;"><a href="{% url "tickets:updatesss" ticket.id %}">{{ ticket.message }}</a></td>-->
        <td><a href="{% url "tickets:updatesss" ticket.id %}">{{ ticket.updated }}</a></td>
        <td><a href="{% url "tickets:updatesss" ticket.id %}">{{ ticket.owner }}</a></td>
        <td><a href="{% url "tickets:updatesss" ticket.id %}">{{ user.username }}</a></td>
      </tr>
    {% endfor %}

  </table>
</div>
  
<section class="jcyc ticket-form">
    {% if user.is_authenticated %}

    <form action="{% url 'tickets:listsss' %}" method="POST">
        {% csrf_token %}
        <div class="jcyc forms-panel">
            <table class="jcyc forms-panel-table">
                <thead>
                    <tr>
                        <td><p class="jcyc list-new-tickets-p">{{ form.id }}</p></td>
                        <td><p class="jcyc list-new-tickets-p">{{ form.subject }}</p></td>
                        <td><p class="jcyc list-new-tickets-p ticket-type">{{ form.ticket_type }}</p></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><p class="jcyc list-new-tickets-p">{{ form.ticket_status }}</p></td>
                        <td><p class="jcyc list-new-tickets-p">{{ form.updated }}</p></td>
                        <td><p class="jcyc list-new-tickets-p">{{ form.owner }}</p></td>
                    </tr>
                    <tr>
                        <td colspan="3"><p class="jcyc list-new-tickets-p">{{ form.message }}</td>
                    </tr>
                    <tr>
                        <td colspan="3" align="center"><input type="submit" name="Submit" value="Submit new bug" /></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </form>
    {% endif %}





    <!--
    <input type="text" name="id" value="" />
    <input type="text" name="subject" value="">
    <input type="text" name="message" value="" />
    <input type="text" name="updated" value="">
    <select name="ticket_status">
      <option value="New">New</option>
      <option value="Read">Read</option>
      <option value="Waiting">Waiting</option>
      <option value="Resolved">Resolved</option>
    </select>
    <select name="ticket_type">
      <option value="Defect">Defect</option>
      <option value="Feature">Read</option>
      <option value="Patch">Patch</option>
    </select>
    <input type="text" name="owner" value="">
    -->



</section>
  

{% endblock content %}

{% block footer %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".list-new-tickets-p input#id_id").attr("readonly", "readonly");
	$(".list-new-tickets-p input#id_id").css("cursor", "default");
});

</script>
{% endblock %}

tickets/templates/tickets/login.html
{% extends "base.html" %}

{% block title %}
Pybugs - Log In
{% endblock title %}

<div class="jcyc asnyc-data"></div>

{% block content %}
  <p>Welcome</p>
  {% if user.is_authenticated %}
  <p>{{ user }}</p>
  {% else %}
  <p>login</p>
  {% endif %}

  <a href="{% url 'tickets:loginsss' %}">Log In</a>
  <a href="{% url 'tickets:logoutsss' %}">Logout</a>
  <a href="{% url 'tickets:newsss' %}">New Ticket</a>
  <a href="{% url 'tickets:listsss' %}">List Tickets</a>

  <section class="jcyc ticket-form">
    <form action="{% url 'tickets:loginsss' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" value="" />
      <input type="password" name="password" value="">
      <input type="submit" name="Login" value="Login" />
      <input type="hidden" name="next" value="{{ next | escape }}"
    </form>
  </section>
  <section>
    <a href="{% url "tickets:loginsss" %}">Login</a><a href="{% url 'tickets:logoutsss' %}">Logout</a>
  </section>
{% endblock content %}

{% block footer %}

{% endblock %}

tickets/templates/tickets/logout.html
{% extends "base.html" %}

{% block title %}
Pybugs - Logged out
{% endblock title %}

<div class="jcyc asnyc-data"></div>
{% block content %}
  <p>Logged Out</p>
  <p>User: {{ user }}</p>
  <p>Password: {{ password }}</p>
  <a href="{% url "tickets:logoutss" %}">Logout</a>
{% endblock content %}

{% block footer %}

{% endblock %}

tickets/templates/tickets/new_ticket.html
{% extends "base.html" %}
{% load rest_framework %}
{% block title %}
Pybugs - Add Bugs
{% endblock title %}

{% block content %}
  <style type="text/css">
    .list-tickets-width { width: 750px; }
  </style>
  {% if user.is_authenticated %}
  <h1>add bugs {{ user }}</h1>
  <a href="{% url "tickets:loginsss" %}">Log In</a>
  <a href="{% url "tickets:logoutsss" %}" %}">Logout</a>
  <a href="{% url "tickets:newsss" %}">New Ticket</a>
  <a href="{% url "tickets:listsss" %}">List Ticket</a>
  {% else %}
  <h1>add bugs</h1>
  {% endif %}
  <div class="jcyc asnyc-data"></div>
  {% if request.user.is_authenticated %}
  <section class="jcyc ticket-form">
    <form action="{% url 'tickets:newsss' %}" method="POST">
      {% csrf_token %}
      <p>{{ form.id }}</p>
      <p>{{ form.subject }}</p>
      <p>{{ form.message }}</p>
      <p>{{ form.ticket_status }}</p>
      <p>{{ form.ticket_type }}</p>
      <p>{{ form.owner }}</p>
      <p>{{ form.updated }}</p>
      <p><input type="submit" name="Create" value="Create new bug" /></p>
    </form>
  </section>
  {% endif %}
{% endblock content %}

{% block footer %}
<script type="text/javascript">

</script>
{% endblock %}

tickets/templates/tickets/ticket_detail.html
{% extends "base.html" %}
{% load rest_framework %}
{% block title %}
Pybugs - Bug {{ ticket.id }}
{% endblock title %}

{% block content %}



    <style type="text/css">
      .jcyc.ticket .sky-blue { background-color: #e6ffff; margin: 15px auto; }
      .top-menu.links {color: #FFFFFF; background-color: #000000; line-height:30px; text-align:right; }
      .top-menu a, .top-menu a:active, .top-menu a:hover { color: #FFFFFF; background-color: #000000; }
      .margin { margin: 0 auto; }


      .txt-align-left { text-align: left; }
      .margin { margin: 0 auto; }
      .list-tickets-width { width: 750px; margin: 0 auto; }
      .top-menu { margin: 0 auto 50px; }
      .top-menu a, .top-menu a:active, .top-menu a:hover { color: #FFFFFF; background-color: #000000 }
      .username { color: #FFFFFF; }
      .ticket-form { margin-top: 50px; text-align: left; }
      .list-new-tickets-p {margin: 15px 0; }
	  .list-new-tickets-p input#id_id { background-color: #dddddd; cursor: default; }
      .message { padding: 10px; border: 1px solid #000000; height: 400px; }
      .ticket-table { width: 750px; }
      #id_id { border: 1px solid #c1c1c1; }
      #id_ticket_type { width: 165px; }
      #id_ticket_status { width:165px; }
    </style>
    <p class="jcyc top-menu links">
      {{ current_user }}
      <a href="{% url 'tickets:loginsss' %}">Log In</a>
      <a href="{% url 'tickets:logoutsss' %}">Logout</a>
      <a href="{% url 'tickets:newsss' %}">New Ticket</a>
      <a href="{% url 'tickets:listsss' %}">List Tickets</a>
      <a href="{% url 'tickets:updatesss' ticket.id %}">Update Tickets</a>
    </p>
<!--

    .txt-align-left { text-align: left; }
    .margin { margin: 0 auto; }
    .list-tickets-width { width: 750px; }
    .top-menu { margin: 0 auto 50px; }
    .top-menu a, .top-menu a:active, .top-menu a:hover { color: #FFFFFF; background-color: #000000 }
    .username { color: #FFFFFF; }
    .ticket-form { margin-top: 50px; text-align: left; }
    .list-new-tickets-p {margin: 15px 0; }

-->


    <div class="jcyc ticket list-tickets-width txt-align-left">
        <table class="jcyc ticket-table">
            <thead>
                <tr>
                    <td width="250"><p class="sky-blue">{{ ticket.id }}</p></td>
                    <td><p class="sky-blue">{{ ticket.subject }}</p></td>
                    <td><p class="sky-blue">{{ ticket.updated }}</p></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td width="250"><p class="sky-blue">{{ ticket.ticket_type }}</p></td>
                    <td><p class="sky-blue">{{ ticket.ticket_status }}</p></td>
                    <td><p class="sky-blue">{{ ticket.owner }}</p></td>
                </tr>
                <tr>
                    <td width="250" colspan="3"><p class="sky-blue message">{{ ticket.message }}</p></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                </tr>
            </tfoot>
        </table>
	  
        <!--<p class="sky-blue"><img src="{{ ticket.attachment }}" width="25" height="25" alt="Thumb" />-->
      <!--<p>By {{ user.username }}</p>-->
      <!--<p class="author">added by {{ user.username }}</p>-->
    </div>

    <section class="jcyc ticket-form list-tickets-width txt-align-left margin">
      {% if user.is_authenticated %}
      <form action="{% url 'tickets:detailsss' ticket.id %}" method="POST"> <!-- {% url 'tickets:newss' %} -->
      <!--<form action="{% url 'tickets:updatess' ticket.id %}" data-method="PUT" enctype="multipart/form-data" novalidate="">-->
        {% csrf_token %}
          <table class="jcyc forms-panel">
            <thead>
                <tr>
                    <td><p class="list-new-tickets-p">{{ form.id }}</p></td>
                    <td><p class="list-new-tickets-p">{{ form.subject }}</p></td>
                    <td><p class="list-new-tickets-p">{{ form.ticket_type }}</p></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><p class="list-new-tickets-p">{{ form.ticket_status }}</p></td>
                    <td><p class="list-new-tickets-p">{{ form.updated }}</p></td>
                    <td><p class="list-new-tickets-p">{{ form.owner }}</p></td>
                </tr>
                <tr>
                    
                    <td><p class="list-new-tickets-p">{{ form.attachment }}</p></td>

                </tr>
                <tr>
                    <td colspan="3"><p class="list-new-tickets-p">{{ form.message }}</p></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" align="center"><input type="submit" name="Submit" value="Log a bug" /></td>
                </tr>
            </tfoot>
              
              
              
          </table>
      </form>
      {% endif %}
    </section>


{% endblock content %}


{% block footer %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".list-new-tickets-p input#id_id").attr("readonly", "readonly");
});

</script>
{% endblock footer %}

tickets/templates/tickets/ticket_details.html
{% extends "base.html" %}
{% load rest_framework %}

{% block title %}
Pybugs - Bug Detail
{% endblock title %}

<div class="jcyc asnyc-data"></div>
{% block content %}
{% endblock content %}

{% block edit_data %}
  <form method="post" action="{% url "tickets:detailsss" %}">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Save" />
  </form>
{% endblock edit_data %}

{% block footer %}
<script type="text/javascript">

</script>
{% endblock footer %}

tickets/templates/tickets/ticket_list.html
{% extends "base.html" %}

<html><body>
<h1>Profiles</h1>
<ul>
    {% for ticket in tickets %}
    <li>{{ ticket.id }}</li>
    {% endfor %}
</ul>
</body></html>